apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rynowak/blazing_backend-frontend:latest
        ports:
        - containerPort: 80
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /healthz
              port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: diag
      protocol: TCP
      port: 8080
      targetPort: 8080