apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blazing-backend
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
    - {key: app, operator: Exists}
  endpoints:
  - port: diag